/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as EditingGuidelinesRouteImport } from './routes/editing-guidelines'
import { Route as BrandGuidelinesRouteImport } from './routes/brand-guidelines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as BrandGuidelinesIndexRouteImport } from './routes/brand-guidelines.index'
import { Route as BrandGuidelinesProfitUniRouteImport } from './routes/brand-guidelines.profit-uni'
import { Route as BrandGuidelinesOrganicVideoRouteImport } from './routes/brand-guidelines.organic-video'
import { Route as BrandGuidelinesBe10xRouteImport } from './routes/brand-guidelines.be10x'
import { Route as BrandGuidelinesAiTvCourseRouteImport } from './routes/brand-guidelines.ai-tv-course'
import { Route as BrandGuidelinesAiTvRouteImport } from './routes/brand-guidelines.ai-tv'
import { Route as TrainingDayIndexRouteImport } from './routes/training.$day.index'
import { Route as TrainingDaySessionRouteImport } from './routes/training.$day.$session'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingGuidelinesRoute = EditingGuidelinesRouteImport.update({
  id: '/editing-guidelines',
  path: '/editing-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandGuidelinesRoute = BrandGuidelinesRouteImport.update({
  id: '/brand-guidelines',
  path: '/brand-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const BrandGuidelinesIndexRoute = BrandGuidelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandGuidelinesRoute,
} as any)
const BrandGuidelinesProfitUniRoute =
  BrandGuidelinesProfitUniRouteImport.update({
    id: '/profit-uni',
    path: '/profit-uni',
    getParentRoute: () => BrandGuidelinesRoute,
  } as any)
const BrandGuidelinesOrganicVideoRoute =
  BrandGuidelinesOrganicVideoRouteImport.update({
    id: '/organic-video',
    path: '/organic-video',
    getParentRoute: () => BrandGuidelinesRoute,
  } as any)
const BrandGuidelinesBe10xRoute = BrandGuidelinesBe10xRouteImport.update({
  id: '/be10x',
  path: '/be10x',
  getParentRoute: () => BrandGuidelinesRoute,
} as any)
const BrandGuidelinesAiTvCourseRoute =
  BrandGuidelinesAiTvCourseRouteImport.update({
    id: '/ai-tv-course',
    path: '/ai-tv-course',
    getParentRoute: () => BrandGuidelinesRoute,
  } as any)
const BrandGuidelinesAiTvRoute = BrandGuidelinesAiTvRouteImport.update({
  id: '/ai-tv',
  path: '/ai-tv',
  getParentRoute: () => BrandGuidelinesRoute,
} as any)
const TrainingDayIndexRoute = TrainingDayIndexRouteImport.update({
  id: '/$day/',
  path: '/$day/',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingDaySessionRoute = TrainingDaySessionRouteImport.update({
  id: '/$day/$session',
  path: '/$day/$session',
  getParentRoute: () => TrainingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-guidelines': typeof BrandGuidelinesRouteWithChildren
  '/editing-guidelines': typeof EditingGuidelinesRoute
  '/training': typeof TrainingRouteWithChildren
  '/brand-guidelines/ai-tv': typeof BrandGuidelinesAiTvRoute
  '/brand-guidelines/ai-tv-course': typeof BrandGuidelinesAiTvCourseRoute
  '/brand-guidelines/be10x': typeof BrandGuidelinesBe10xRoute
  '/brand-guidelines/organic-video': typeof BrandGuidelinesOrganicVideoRoute
  '/brand-guidelines/profit-uni': typeof BrandGuidelinesProfitUniRoute
  '/brand-guidelines/': typeof BrandGuidelinesIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/training/$day/$session': typeof TrainingDaySessionRoute
  '/training/$day/': typeof TrainingDayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editing-guidelines': typeof EditingGuidelinesRoute
  '/brand-guidelines/ai-tv': typeof BrandGuidelinesAiTvRoute
  '/brand-guidelines/ai-tv-course': typeof BrandGuidelinesAiTvCourseRoute
  '/brand-guidelines/be10x': typeof BrandGuidelinesBe10xRoute
  '/brand-guidelines/organic-video': typeof BrandGuidelinesOrganicVideoRoute
  '/brand-guidelines/profit-uni': typeof BrandGuidelinesProfitUniRoute
  '/brand-guidelines': typeof BrandGuidelinesIndexRoute
  '/training': typeof TrainingIndexRoute
  '/training/$day/$session': typeof TrainingDaySessionRoute
  '/training/$day': typeof TrainingDayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-guidelines': typeof BrandGuidelinesRouteWithChildren
  '/editing-guidelines': typeof EditingGuidelinesRoute
  '/training': typeof TrainingRouteWithChildren
  '/brand-guidelines/ai-tv': typeof BrandGuidelinesAiTvRoute
  '/brand-guidelines/ai-tv-course': typeof BrandGuidelinesAiTvCourseRoute
  '/brand-guidelines/be10x': typeof BrandGuidelinesBe10xRoute
  '/brand-guidelines/organic-video': typeof BrandGuidelinesOrganicVideoRoute
  '/brand-guidelines/profit-uni': typeof BrandGuidelinesProfitUniRoute
  '/brand-guidelines/': typeof BrandGuidelinesIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/training/$day/$session': typeof TrainingDaySessionRoute
  '/training/$day/': typeof TrainingDayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-guidelines'
    | '/editing-guidelines'
    | '/training'
    | '/brand-guidelines/ai-tv'
    | '/brand-guidelines/ai-tv-course'
    | '/brand-guidelines/be10x'
    | '/brand-guidelines/organic-video'
    | '/brand-guidelines/profit-uni'
    | '/brand-guidelines/'
    | '/training/'
    | '/training/$day/$session'
    | '/training/$day/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editing-guidelines'
    | '/brand-guidelines/ai-tv'
    | '/brand-guidelines/ai-tv-course'
    | '/brand-guidelines/be10x'
    | '/brand-guidelines/organic-video'
    | '/brand-guidelines/profit-uni'
    | '/brand-guidelines'
    | '/training'
    | '/training/$day/$session'
    | '/training/$day'
  id:
    | '__root__'
    | '/'
    | '/brand-guidelines'
    | '/editing-guidelines'
    | '/training'
    | '/brand-guidelines/ai-tv'
    | '/brand-guidelines/ai-tv-course'
    | '/brand-guidelines/be10x'
    | '/brand-guidelines/organic-video'
    | '/brand-guidelines/profit-uni'
    | '/brand-guidelines/'
    | '/training/'
    | '/training/$day/$session'
    | '/training/$day/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandGuidelinesRoute: typeof BrandGuidelinesRouteWithChildren
  EditingGuidelinesRoute: typeof EditingGuidelinesRoute
  TrainingRoute: typeof TrainingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing-guidelines': {
      id: '/editing-guidelines'
      path: '/editing-guidelines'
      fullPath: '/editing-guidelines'
      preLoaderRoute: typeof EditingGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-guidelines': {
      id: '/brand-guidelines'
      path: '/brand-guidelines'
      fullPath: '/brand-guidelines'
      preLoaderRoute: typeof BrandGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/brand-guidelines/': {
      id: '/brand-guidelines/'
      path: '/'
      fullPath: '/brand-guidelines/'
      preLoaderRoute: typeof BrandGuidelinesIndexRouteImport
      parentRoute: typeof BrandGuidelinesRoute
    }
    '/brand-guidelines/profit-uni': {
      id: '/brand-guidelines/profit-uni'
      path: '/profit-uni'
      fullPath: '/brand-guidelines/profit-uni'
      preLoaderRoute: typeof BrandGuidelinesProfitUniRouteImport
      parentRoute: typeof BrandGuidelinesRoute
    }
    '/brand-guidelines/organic-video': {
      id: '/brand-guidelines/organic-video'
      path: '/organic-video'
      fullPath: '/brand-guidelines/organic-video'
      preLoaderRoute: typeof BrandGuidelinesOrganicVideoRouteImport
      parentRoute: typeof BrandGuidelinesRoute
    }
    '/brand-guidelines/be10x': {
      id: '/brand-guidelines/be10x'
      path: '/be10x'
      fullPath: '/brand-guidelines/be10x'
      preLoaderRoute: typeof BrandGuidelinesBe10xRouteImport
      parentRoute: typeof BrandGuidelinesRoute
    }
    '/brand-guidelines/ai-tv-course': {
      id: '/brand-guidelines/ai-tv-course'
      path: '/ai-tv-course'
      fullPath: '/brand-guidelines/ai-tv-course'
      preLoaderRoute: typeof BrandGuidelinesAiTvCourseRouteImport
      parentRoute: typeof BrandGuidelinesRoute
    }
    '/brand-guidelines/ai-tv': {
      id: '/brand-guidelines/ai-tv'
      path: '/ai-tv'
      fullPath: '/brand-guidelines/ai-tv'
      preLoaderRoute: typeof BrandGuidelinesAiTvRouteImport
      parentRoute: typeof BrandGuidelinesRoute
    }
    '/training/$day/': {
      id: '/training/$day/'
      path: '/$day'
      fullPath: '/training/$day/'
      preLoaderRoute: typeof TrainingDayIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/$day/$session': {
      id: '/training/$day/$session'
      path: '/$day/$session'
      fullPath: '/training/$day/$session'
      preLoaderRoute: typeof TrainingDaySessionRouteImport
      parentRoute: typeof TrainingRoute
    }
  }
}

interface BrandGuidelinesRouteChildren {
  BrandGuidelinesAiTvRoute: typeof BrandGuidelinesAiTvRoute
  BrandGuidelinesAiTvCourseRoute: typeof BrandGuidelinesAiTvCourseRoute
  BrandGuidelinesBe10xRoute: typeof BrandGuidelinesBe10xRoute
  BrandGuidelinesOrganicVideoRoute: typeof BrandGuidelinesOrganicVideoRoute
  BrandGuidelinesProfitUniRoute: typeof BrandGuidelinesProfitUniRoute
  BrandGuidelinesIndexRoute: typeof BrandGuidelinesIndexRoute
}

const BrandGuidelinesRouteChildren: BrandGuidelinesRouteChildren = {
  BrandGuidelinesAiTvRoute: BrandGuidelinesAiTvRoute,
  BrandGuidelinesAiTvCourseRoute: BrandGuidelinesAiTvCourseRoute,
  BrandGuidelinesBe10xRoute: BrandGuidelinesBe10xRoute,
  BrandGuidelinesOrganicVideoRoute: BrandGuidelinesOrganicVideoRoute,
  BrandGuidelinesProfitUniRoute: BrandGuidelinesProfitUniRoute,
  BrandGuidelinesIndexRoute: BrandGuidelinesIndexRoute,
}

const BrandGuidelinesRouteWithChildren = BrandGuidelinesRoute._addFileChildren(
  BrandGuidelinesRouteChildren,
)

interface TrainingRouteChildren {
  TrainingIndexRoute: typeof TrainingIndexRoute
  TrainingDaySessionRoute: typeof TrainingDaySessionRoute
  TrainingDayIndexRoute: typeof TrainingDayIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingIndexRoute: TrainingIndexRoute,
  TrainingDaySessionRoute: TrainingDaySessionRoute,
  TrainingDayIndexRoute: TrainingDayIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandGuidelinesRoute: BrandGuidelinesRouteWithChildren,
  EditingGuidelinesRoute: EditingGuidelinesRoute,
  TrainingRoute: TrainingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
